#!/bin/bash
#macarraotrybe - cria enquanto explica os comandos todas as pastas onde irão os exercícios de acordo com o currículo da turma 20.
#autora - Nádia Dutra

echo "Olá"
sleep 2 
echo "Vamos criar toda a hierarquia de pastas onde você colocará os exercícios que fará durante o ano."
sleep 3
echo
echo "Primeiro vamos verificar se estamos na home do atual usuário."
sleep 2

#test1 - verifica se a pessoa estudante conhece o pwd
while test "$E_PWD" != "pwd"; do
	echo "Digite o comando que nos mostra onde estamos: "
	sleep 1
	printf "$"
	read E_PWD
done
pwd
sleep 2
echo

#test2 - verifica se a pessoa estudante sabe chegar na home
echo "Como o usuário atual é o $USER, a sua pasta home é a $HOME."
sleep 2
if [ "$PWD" = "$HOME" ]; then
	echo "E como o pwd nos mostrou é aqui mesmo."
	sleep 2
else
	echo "Então precisamos ir para o diretório home."
	sleep 2
	while test "$E_CD" != "cd"; do
		echo "Digite o comando que muda o diretório: "
		sleep 1
		printf "$"
		read E_CD
	done
	while [ "$E_TIO" != "~" ] && [ "$E_TIO" != "$HOME" ]; do
		echo "Agora o argumento do comando: "
		sleep 1
		printf "\$cd "
		read E_TIO
		if [ "$E_TIO" = "~" ] || [ "$E_TIO" = "$HOME" ]; then
			cd $HOME
		fi
		sleep 1
	done
	echo "pwd novamente para conferir"
	sleep 2
	echo "\$pwd "
	sleep 1
	pwd
fi
sleep 1

#test3 - verifica se a pessoa estudante sabe criar um novo diretório
echo "Precisamos agora só fazer as pastas"
sleep 2
while test "$E_MKDIR" != "mkdir"; do
	echo "Qual comando cria uma pasta?"
	sleep 1
	printf "$"
	read E_MKDIR
done

sleep 1
echo "Isso mesmo!"
sleep 1
echo "Vou criar todos os diretórios pra você, veja."
sleep 2
printf "$"
sleep 1
printf "mkdir "
sleep 1
printf "trybe_exercicios"
sleep 1
mkdir trybe_exercicios